### PR TITLE
Implemented support for interger only numbers and max value for numbers.

### PR DESCRIPTION
**Pull request by dan-h-ch**

### CODE REVIEW

**Comment by csapinoso** [comment]
I was thinking rather than defining new types for integers and decimals, we should probably just expose the property on the existing number type that would dictate whether it should accept Integers or decimals only

**Comment by dan-h-ch** [comment]
Implemented suggestion.

**Comment by dan-h-ch** [comment]
Removed custom type (number-integer) in this case, from CMS. Logic is handled before it is passed to CMS.

**Comment by dan-h-ch** [comment]
Replaced by other PR.

**Pull request closed without merging**
